language: node_js

cache:
  directories:
    - $HOME/.npm

node_js:
  - '10'
  - '12'
  - '14'

before_install:
  - npm i -g npm@6

install:
  - travis_retry npm install

script:
  - npm run lint
  - npm test

after_success: test -z "$COV_PUB" || npm run check